// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachGUI(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttachGUI'](arg1, arg2, arg3);
}

export function CancelPing() {
  return window['go']['main']['App']['CancelPing']();
}

export function ClearCertPin(arg1) {
  return window['go']['main']['App']['ClearCertPin'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyLink(arg1) {
  return window['go']['main']['App']['CopyLink'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportLinks(arg1) {
  return window['go']['main']['App']['ImportLinks'](arg1);
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function NodeConfigPreview(arg1) {
  return window['go']['main']['App']['NodeConfigPreview'](arg1);
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function PingNode(arg1) {
  return window['go']['main']['App']['PingNode'](arg1);
}

export function ProxyStatus() {
  return window['go']['main']['App']['ProxyStatus']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RenameNode(arg1, arg2) {
  return window['go']['main']['App']['RenameNode'](arg1, arg2);
}

export function SelectNode(arg1) {
  return window['go']['main']['App']['SelectNode'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function Startup() {
  return window['go']['main']['App']['Startup']();
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function Toggle(arg1) {
  return window['go']['main']['App']['Toggle'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
