// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachGUI(arg1:main.Notifier,arg2:main.WindowController,arg3:main.TrayController):Promise<void>;

export function CancelPing():Promise<void>;

export function ClearCertPin(arg1:string):Promise<void>;

export function ConfigPath():Promise<string>;

export function Connect(arg1:string):Promise<main.StateView>;

export function CopyLink(arg1:string):Promise<string>;

export function DeleteNode(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetLogs(arg1:number):Promise<Array<main.LogEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetState():Promise<main.StateView>;

export function ImportLinks(arg1:string):Promise<main.ImportResult>;

export function ListConfigs():Promise<Array<main.NodeView>>;

export function ListNodes():Promise<Array<main.NodeView>>;

export function NodeConfigPreview(arg1:string):Promise<string>;

export function PingAll():Promise<Array<main.PingResult>>;

export function PingNode(arg1:string):Promise<main.PingResult>;

export function ProxyStatus():Promise<main.ProxyStatus>;

export function Quit():Promise<void>;

export function RenameNode(arg1:string,arg2:string):Promise<void>;

export function SelectNode(arg1:string):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<main.StateView>;

export function Shutdown():Promise<void>;

export function Startup():Promise<void>;

export function State():Promise<main.StateView>;

export function Toggle(arg1:string):Promise<main.StateView>;

export function UpdateSettings(arg1:main.Settings):Promise<main.StateView>;

export function WindowClose():Promise<void>;

export function WindowHide():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
